#!/usr/bin/env bash
# GENERATED by /add-shortcut (make-shortcut.sh) — regenerate, don't hand-edit.
# Runner for "clip-db pipeline": run the command, then pause so a terminal launch stays
# readable (KDE closes the window on exit otherwise). Deployed (COPIED, review-
# gated) into ethan's ~/.local/bin by install.sh — never run from the repo tree.
set -uo pipefail
/home/ethan/.local/bin/clip-db-pipeline
status=$?
if [ -t 0 ]; then
  echo
  read -n1 -rp "Done (exit $status). Press any key to close…"
  echo
fi
exit "$status"
