#!/usr/bin/env bash
# GENERATED by /add-shortcut (make-shortcut.sh) — regenerate, don't hand-edit.
# Runner for "Jellyfin Server": run the command, then pause so a terminal launch stays
# readable (KDE closes the window on exit otherwise). Deployed (COPIED, review-
# gated) into ethan's ~/.local/bin by install.sh — never run from the repo tree.
set -uo pipefail
bash -c 'docker compose up -d && sleep 3 && xdg-open http://localhost:8096'
status=$?
if [ -t 0 ]; then
  echo
  read -n1 -rp "Done (exit $status). Press any key to close…"
  echo
fi
exit "$status"
