#!/usr/bin/env bash
#
# build-claude-md.sh  —  MASTER build script for dev's CLAUDE.md
#
# Two phases:
#   1. Regenerate every section under sections/ by running its generator script.
#   2. Assemble CLAUDE.md from CLAUDE.md.blueprint, replacing each whole-line
#      {{token}} with the contents of sections/<token>.md.
#
# The resulting CLAUDE.md is intended to be symlinked to dev's global config:
#   ln -s /srv/dev/repos/my-system/users/dev/CLAUDE.md ~/.claude/CLAUDE.md
#
# Add a new section later by (a) writing a generator that emits
# sections/<name>.md and (b) adding {{<name>}} to the blueprint. Register the
# generator in SECTION_GENERATORS below so this script refreshes it too.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
BLUEPRINT="$REPO_ROOT/CLAUDE.md.blueprint"
SECTIONS_DIR="$REPO_ROOT/sections"
OUT_FILE="$REPO_ROOT/CLAUDE.md"

# Section generators to run in phase 1 (add more as sections are introduced).
SECTION_GENERATORS=(
  "$REPO_ROOT/scripts/generate-repo-descriptions.sh"
)

# --- phase 1: refresh sections ---------------------------------------------
echo "==> Regenerating sections"
for gen in "${SECTION_GENERATORS[@]}"; do
  echo "  - $(basename "$gen")"
  "$gen"
done

# --- phase 2: assemble CLAUDE.md from the blueprint ------------------------
echo "==> Assembling $OUT_FILE from $(basename "$BLUEPRINT")"
[ -f "$BLUEPRINT" ] || { echo "error: blueprint not found: $BLUEPRINT" >&2; exit 1; }

tmp="$(mktemp "$OUT_FILE.XXXXXX")"
trap 'rm -f "$tmp"' EXIT

{
  echo "<!-- GENERATED by build-claude-md.sh — do NOT edit directly. -->"
  echo "<!-- Edit CLAUDE.md.blueprint (structure) or the section generators (content), then re-run build-claude-md.sh. -->"
  echo
} > "$tmp"

# Stream the blueprint; expand whole-line {{token}} placeholders.
while IFS= read -r line || [ -n "$line" ]; do
  trimmed="${line#"${line%%[![:space:]]*}"}"      # ltrim
  trimmed="${trimmed%"${trimmed##*[![:space:]]}"}" # rtrim
  if [[ "$trimmed" =~ ^\{\{([a-z0-9._-]+)\}\}$ ]]; then
    name="${BASH_REMATCH[1]}"
    sec="$SECTIONS_DIR/$name.md"
    if [ -f "$sec" ]; then
      cat "$sec"
    else
      echo "<!-- MISSING SECTION: $name ($sec not found) -->"
    fi
  elif [[ "$trimmed" =~ ^\<!--.*--\>$ ]]; then
    : # drop the blueprint's own maintainer-guidance comment lines
  else
    printf '%s\n' "$line"
  fi
done < "$BLUEPRINT" >> "$tmp"

chmod 664 "$tmp"   # mktemp defaults to 0600; restore group read for the developers group
mv "$tmp" "$OUT_FILE"
trap - EXIT
echo "==> Wrote $OUT_FILE"
