#!/usr/bin/env bash
#
# generate-repo-descriptions.sh
#
# Produce the "repo descriptions" SECTION of the assembled CLAUDE.md. It pairs
# each repo directory under /srv/dev/repos with its GitHub *description*.
#
# This does NOT write CLAUDE.md directly — it writes a section file under
# sections/, which build-claude-md.sh embeds into the CLAUDE.md blueprint.
#
# The GitHub description is repo metadata (the one-liner on the repo page), not
# a file in the git tree, so it cannot be read from a local clone — it is
# fetched from the GitHub API. Public repos need no auth; private repos require
# dev's PAT, which is read at runtime from the git credential helper
# (~/.git-credentials). The token is NEVER hardcoded or printed here.
#
# Regenerate whenever repos are added/removed or descriptions change (normally
# invoked for you by build-claude-md.sh):
#   /srv/dev/repos/my-system/users/dev/scripts/generate-repo-descriptions.sh

set -euo pipefail

REPOS_DIR="${REPOS_DIR:-/srv/dev/repos}"
SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_FILE="${OUT_FILE:-$REPO_ROOT/sections/repo-descriptions.md}"
API="https://api.github.com"

# --- token -----------------------------------------------------------------
# Pull the PAT from the git credential helper once. Sending it on every call
# also lifts us off the low unauthenticated API rate limit. Empty if none.
TOKEN="$(printf 'protocol=https\nhost=github.com\n\n' \
  | git credential fill 2>/dev/null \
  | sed -n 's/^password=//p' || true)"

# Build curl auth args as an array so the header survives word-splitting.
# (A bare ${TOKEN:+-H "..."} re-splits after expansion and mangles the header.)
AUTH_ARGS=()
[ -n "$TOKEN" ] && AUTH_ARGS=(-H "Authorization: Bearer $TOKEN")

# --- helpers ---------------------------------------------------------------

# origin URL -> "owner/repo", or non-zero exit if not a GitHub remote.
slug_from_url() {
  local url="$1"
  case "$url" in
    git@github.com:*)       url="${url#git@github.com:}" ;;
    ssh://git@github.com/*) url="${url#ssh://git@github.com/}" ;;
    https://github.com/*)   url="${url#https://github.com/}" ;;
    http://github.com/*)    url="${url#http://github.com/}" ;;
    *) return 1 ;;
  esac
  printf '%s' "${url%.git}"
}

# owner/repo -> description text, or a parenthetical status marker.
fetch_description() {
  local slug="$1" resp http body desc
  resp="$(curl -sS -w $'\n%{http_code}' \
      "${AUTH_ARGS[@]}" \
      -H "Accept: application/vnd.github+json" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      "$API/repos/$slug" 2>/dev/null)" || { printf '(error contacting GitHub)'; return; }
  http="${resp##*$'\n'}"
  body="${resp%$'\n'*}"
  case "$http" in
    200)
      desc="$(printf '%s' "$body" | jq -r '.description // ""')"
      [ -n "$desc" ] && printf '%s' "$desc" || printf '(no description set)'
      ;;
    404)     printf '(not found or dev lacks access)' ;;
    401|403) printf '(unauthorized — check dev PAT)' ;;
    *)       printf '(HTTP %s)' "$http" ;;
  esac
}

# --- build -----------------------------------------------------------------
tracked=""   # lines for GitHub-backed repos
local_only="" # lines for repos with no GitHub remote

for dir in "$REPOS_DIR"/*/; do
  [ -d "$dir" ] || continue
  name="$(basename "$dir")"
  url="$(git -C "$dir" remote get-url origin 2>/dev/null || true)"

  path="$REPOS_DIR/$name"

  if [ -z "$url" ]; then
    local_only+="- **$name** — \`$path\` — local-only (no GitHub remote)"$'\n'
    continue
  fi

  if slug="$(slug_from_url "$url")"; then
    desc="$(fetch_description "$slug")"
    tracked+="- **$name** — \`$path\` (\`$slug\`) — $desc"$'\n'
  else
    tracked+="- **$name** — \`$path\` (\`$url\`) — (non-GitHub remote)"$'\n'
  fi
done

# --- write (atomically) ----------------------------------------------------
mkdir -p "$(dirname "$OUT_FILE")"
tmp="$(mktemp "$OUT_FILE.XXXXXX")"
trap 'rm -f "$tmp"' EXIT

{
  echo "<!-- SECTION: repo-descriptions -->"
  echo "<!-- AUTO-GENERATED by scripts/generate-repo-descriptions.sh — do not edit by hand. -->"
  echo "<!-- Last generated: $(date -Is) -->"
  echo
  echo "## Ethan's repositories live under \`$REPOS_DIR\`"
  echo
  echo "**All of Ethan's projects/repos are directories under \`$REPOS_DIR\`.**"
  echo "When Ethan names a repository — or just says \"repo\", \"the repo\", \"my"
  echo "project\", etc. — resolve it to a directory in the list below and work there."
  echo "Do this by default:"
  echo
  echo "- **Always look here first.** Before saying a repo can't be found, or asking"
  echo "  where it is, check \`$REPOS_DIR\` — e.g. \`ls $REPOS_DIR\` or"
  echo "  \`$REPOS_DIR/<name>\`. The name Ethan says is the directory name."
  echo "- Match loosely: names may differ in case/hyphenation from what Ethan types."
  echo "- Each entry below gives the directory's **absolute path** — cd/read there"
  echo "  directly; don't re-discover it."
  echo "- The description is the repo's GitHub metadata (not the README), for"
  echo "  recognizing which project is which."
  echo
  echo "### GitHub-tracked"
  echo
  printf '%s' "$tracked"
  if [ -n "$local_only" ]; then
    echo
    echo "### Local-only (no GitHub remote)"
    echo
    printf '%s' "$local_only"
  fi
} > "$tmp"

chmod 664 "$tmp"   # mktemp defaults to 0600; restore group read for the developers group
mv "$tmp" "$OUT_FILE"
trap - EXIT
echo "Wrote $OUT_FILE"
