#!/usr/bin/env bash
# GENERATED by /add-shortcut (make-shortcut.sh) — regenerate, don't hand-edit.
# Runner for "Deploy my-system config": run the command, then pause so a terminal launch stays
# readable (KDE closes the window on exit otherwise).
set -uo pipefail
/srv/dev/repos/my-system/users/install.sh
status=$?
if [ -t 0 ]; then
  echo
  read -n1 -rp "Done (exit $status). Press any key to close…"
  echo
fi
exit "$status"
